#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NSString *CCNMRequestedMode NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMRequestedMode const CCNMRequestedModeSystemDefault;
FOUNDATION_EXPORT CCNMRequestedMode const CCNMRequestedModeN78Preferred;

typedef NSString *CCNMAppliedPolicy NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyUnknown;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyApplying;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyVerifiedSystemDefault;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyVerifiedN78Only;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyDiverged;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyRecoveryRequired;

typedef NSString *CCNMServingState NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateNRN78;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateNROther;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateLTE;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateOther;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateUnknown;

typedef NSString *CCNMRecoveryState NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateClean;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateEnablePending;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateEnabledWithBaseline;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRestorePending;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateCarrierResetPending;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateCarrierResetFailed;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRebootRequired;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRecoveryFailed;

typedef NSString *CCNMN78PolicyErrorCode NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorNone;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorBusy;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUnsupportedTarget;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUnsafeSubscription;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorInvalidBandInfo;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorN78Unavailable;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorInvalidRecords;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUUIDDrift;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorBaselineIncompatible;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorPersistence;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorSetterFailed;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorSetterUncertain;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorReadBackMismatch;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorRecoveryRequired;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorCarrierResetFailed;

FOUNDATION_EXPORT NSString *const CCNMN78PolicySummarySuccessKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryOperationKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryStateKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRequestedModeKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryAppliedPolicyKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRecoveryStateKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryErrorCodeKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryErrorKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRequiresRebootKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryMayWriteKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryMayUninstallKey;
/// True only when a restore already passed complete modem read-back and retired
/// its baseline, but crashed before the final clean-state rewrite. Recovery may
/// finish the durable bookkeeping after revalidating the live complete BandInfo;
/// it must not issue another setter call.
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryCleanupCheckpointRecoverableKey;
/// The NR band set the policy has verified as applied, ascending. Absent unless
/// the summary describes a stable enabled state, so a reader must treat a missing
/// value as "no selection is in effect" rather than substituting a default.
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryTargetNRBandsKey;

NS_ASSUME_NONNULL_END
