#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NSString *CCNMRequestedMode NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMRequestedMode const CCNMRequestedModeSystemDefault;
FOUNDATION_EXPORT CCNMRequestedMode const CCNMRequestedModeN78Preferred;

typedef NSString *CCNMAppliedPolicy NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyUnknown;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyApplying;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyVerifiedSystemDefault;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyVerifiedN78Only;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyDiverged;
FOUNDATION_EXPORT CCNMAppliedPolicy const CCNMAppliedPolicyRecoveryRequired;

typedef NSString *CCNMServingState NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateNRN78;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateNROther;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateLTE;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateOther;
FOUNDATION_EXPORT CCNMServingState const CCNMServingStateUnknown;

typedef NSString *CCNMRecoveryState NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateClean;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateEnablePending;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateEnabledWithBaseline;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRestorePending;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRebootRequired;
FOUNDATION_EXPORT CCNMRecoveryState const CCNMRecoveryStateRecoveryFailed;

typedef NSString *CCNMN78PolicyErrorCode NS_TYPED_ENUM;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorNone;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorBusy;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUnsupportedTarget;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUnsafeSubscription;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorInvalidBandInfo;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorN78Unavailable;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorInvalidRecords;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorUUIDDrift;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorBaselineIncompatible;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorPersistence;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorSetterFailed;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorSetterUncertain;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorReadBackMismatch;
FOUNDATION_EXPORT CCNMN78PolicyErrorCode const CCNMN78PolicyErrorRecoveryRequired;

FOUNDATION_EXPORT NSString *const CCNMN78PolicySummarySuccessKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryOperationKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryStateKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRequestedModeKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryAppliedPolicyKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRecoveryStateKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryErrorCodeKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryErrorKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryRequiresRebootKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryMayWriteKey;
FOUNDATION_EXPORT NSString *const CCNMN78PolicySummaryMayUninstallKey;

NS_ASSUME_NONNULL_END
